"""
app.py
------
Main Flask application for NoteTube AI.

Endpoints:
    POST /api/generate           Full pipeline: URL -> transcript -> AI notes -> DOCX
    GET  /api/download/<filename> Stream a previously generated .docx file
    GET  /api/health              Simple liveness check
"""

import os
import re

from flask import Flask, request, jsonify, send_from_directory, abort
from flask_cors import CORS
from dotenv import load_dotenv

from transcript import get_transcript, InvalidYouTubeURLError, TranscriptUnavailableError
from ai import generate_notes, AIGenerationError, MissingAPIKeyError
from doc_generator import generate_docx

load_dotenv()

app = Flask(__name__)

_allowed_origins = os.environ.get("CORS_ALLOWED_ORIGINS", "*")
_origins_list = [o.strip() for o in _allowed_origins.split(",")] if _allowed_origins != "*" else "*"
CORS(app, resources={r"/api/*": {"origins": _origins_list}})

TEMP_FILE_DIR = os.environ.get("TEMP_FILE_DIR", "temp_files")
os.makedirs(TEMP_FILE_DIR, exist_ok=True)

# Filenames generated by doc_generator.py always match this shape:
# <safe_title>_<10-hex-char-uuid>.docx
_SAFE_FILENAME_PATTERN = re.compile(r"^[a-zA-Z0-9_-]+\.docx$")


def _error_response(message: str, status_code: int = 400):
    return jsonify({"success": False, "error": message}), status_code


@app.route("/api/health", methods=["GET"])
def health_check():
    return jsonify({"success": True, "status": "ok"}), 200


@app.route("/api/generate", methods=["POST"])
def generate():
    """
    Full pipeline endpoint.

    Expects JSON body: { "url": "https://www.youtube.com/watch?v=..." }

    Returns on success:
        {
            "success": true,
            "markdown_content": "<full markdown notes>",
            "download_filename": "<generated>.docx",
            "download_url": "/api/download/<generated>.docx"
        }

    Returns on failure:
        { "success": false, "error": "<human readable message>" }
    """
    try:
        payload = request.get_json(silent=True)
    except Exception:
        payload = None

    if not payload or "url" not in payload or not str(payload["url"]).strip():
        return _error_response("Request body must include a non-empty 'url' field.", 400)

    url = str(payload["url"]).strip()

    # --- Step 1: Transcript extraction -----------------------------------
    try:
        transcript_text = get_transcript(url)
    except InvalidYouTubeURLError as exc:
        return _error_response(str(exc), 400)
    except TranscriptUnavailableError as exc:
        return _error_response(str(exc), 422)
    except Exception as exc:  # noqa: BLE001
        return _error_response(f"Unexpected error extracting transcript: {exc}", 500)

    # --- Step 2: AI note generation ---------------------------------------
    try:
        markdown_content = generate_notes(transcript_text)
    except MissingAPIKeyError as exc:
        return _error_response(str(exc), 500)
    except AIGenerationError as exc:
        return _error_response(str(exc), 502)
    except Exception as exc:  # noqa: BLE001
        return _error_response(f"Unexpected error generating notes: {exc}", 500)

    # --- Step 3: DOCX generation --------------------------------------------
    try:
        video_title = payload.get("title") or "NoteTube_AI_Notes"
        filepath = generate_docx(markdown_content, video_title=video_title, temp_dir=TEMP_FILE_DIR)
        filename = os.path.basename(filepath)
    except Exception as exc:  # noqa: BLE001
        return _error_response(f"Unexpected error generating document: {exc}", 500)

    return jsonify({
        "success": True,
        "markdown_content": markdown_content,
        "download_filename": filename,
        "download_url": f"/api/download/{filename}",
    }), 200


@app.route("/api/download/<path:filename>", methods=["GET"])
def download(filename):
    """
    Stream a generated .docx file to the browser.

    Rejects any filename that doesn't match the expected generated-file
    shape, to prevent path traversal or access to arbitrary server files.
    """
    if not _SAFE_FILENAME_PATTERN.match(filename):
        abort(400, description="Invalid filename.")

    full_path = os.path.join(TEMP_FILE_DIR, filename)
    if not os.path.isfile(full_path):
        abort(404, description="File not found. It may have expired or already been downloaded.")

    return send_from_directory(
        TEMP_FILE_DIR,
        filename,
        as_attachment=True,
        mimetype="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    )


@app.errorhandler(404)
def not_found(_error):
    return jsonify({"success": False, "error": "Resource not found."}), 404


@app.errorhandler(500)
def server_error(_error):
    return jsonify({"success": False, "error": "Internal server error."}), 500


if __name__ == "__main__":
    port = int(os.environ.get("FLASK_PORT", 5000))
    debug = os.environ.get("FLASK_DEBUG", "True").lower() == "true"
    app.run(host=os.environ.get("FLASK_HOST", "0.0.0.0"), port=port, debug=debug)
